//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivecall
    {
        public long id { get; set; }
        public long OnCAllPersonID { get; set; }
        public long RequestPersonId { get; set; }
        public System.DateTime CallReqTime { get; set; }
        public bool EMATALA { get; set; }
        public string TAT { get; set; }
        public string PatientNumber { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<System.DateTime> CallEndedTime { get; set; }
        public Nullable<long> CallEndedBy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string ReasonToEndCall { get; set; }
    
        public virtual tblOnCall tblOnCall { get; set; }
    }
}
