//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnCallPeople
    {
        public tblOnCallPeople()
        {
            this.tblOnCalls = new HashSet<tblOnCall>();
        }
    
        public long id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> PhoneNumber { get; set; }
        public Nullable<decimal> CellNO { get; set; }
        public string EmailAddress { get; set; }
        public long PracticeId { get; set; }
        public long SpecialityId { get; set; }
        public bool IsCredentialed { get; set; }
        public bool IsActive { get; set; }
        public bool CanRequest { get; set; }
        public string Picture { get; set; }
        public string CallCarrier { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string FullName { get; set; }
        public bool IsEmtala { get; set; }
    
        public virtual ICollection<tblOnCall> tblOnCalls { get; set; }
        public virtual tblSpeciality tblSpeciality { get; set; }
        public virtual tblSpeciality tblSpeciality1 { get; set; }
    }
}
