//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPractice
    {
        public long id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> PhoneNumber { get; set; }
        public Nullable<decimal> FaxNumber { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> RequiresBackup { get; set; }
        public string BackupPolicy { get; set; }
    }
}
