//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpeciality
    {
        public tblSpeciality()
        {
            this.tblOnCalls = new HashSet<tblOnCall>();
            this.tblOnCallPeoples = new HashSet<tblOnCallPeople>();
            this.tblOnCallPeoples1 = new HashSet<tblOnCallPeople>();
        }
    
        public long id { get; set; }
        public string Speciality { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<tblOnCall> tblOnCalls { get; set; }
        public virtual ICollection<tblOnCallPeople> tblOnCallPeoples { get; set; }
        public virtual ICollection<tblOnCallPeople> tblOnCallPeoples1 { get; set; }
    }
}
