//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TelaCallEntities : DbContext
    {
        public TelaCallEntities()
            : base("name=TelaCallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mtblRole> mtblRoles { get; set; }
        public DbSet<tblActivecall> tblActivecalls { get; set; }
        public DbSet<tblNote> tblNotes { get; set; }
        public DbSet<tblOnCall> tblOnCalls { get; set; }
        public DbSet<tblOnCallPeople> tblOnCallPeoples { get; set; }
        public DbSet<tblPractice> tblPractices { get; set; }
        public DbSet<tblSpeciality> tblSpecialities { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    
        public virtual ObjectResult<Web_Practices_Result> Web_Practices(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_Practices_Result>("Web_Practices", idParameter);
        }
    
        public virtual ObjectResult<Web_Roles_Result> Web_Roles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_Roles_Result>("Web_Roles");
        }
    
        public virtual ObjectResult<Nullable<int>> Web_SaveOnCallPeople(Nullable<long> id, string onCAllPersonID, string firstName, string lastName, Nullable<decimal> phoneNumber, Nullable<decimal> cellNO, string emailAddress, Nullable<long> practiceId, Nullable<long> specialityId, Nullable<bool> isEmtala, Nullable<bool> isCredentialed, Nullable<bool> canRequest, string callCarrier, string userId, string picture)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var onCAllPersonIDParameter = onCAllPersonID != null ?
                new ObjectParameter("OnCAllPersonID", onCAllPersonID) :
                new ObjectParameter("OnCAllPersonID", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var phoneNumberParameter = phoneNumber.HasValue ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(decimal));
    
            var cellNOParameter = cellNO.HasValue ?
                new ObjectParameter("CellNO", cellNO) :
                new ObjectParameter("CellNO", typeof(decimal));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var practiceIdParameter = practiceId.HasValue ?
                new ObjectParameter("PracticeId", practiceId) :
                new ObjectParameter("PracticeId", typeof(long));
    
            var specialityIdParameter = specialityId.HasValue ?
                new ObjectParameter("SpecialityId", specialityId) :
                new ObjectParameter("SpecialityId", typeof(long));
    
            var isEmtalaParameter = isEmtala.HasValue ?
                new ObjectParameter("IsEmtala", isEmtala) :
                new ObjectParameter("IsEmtala", typeof(bool));
    
            var isCredentialedParameter = isCredentialed.HasValue ?
                new ObjectParameter("IsCredentialed", isCredentialed) :
                new ObjectParameter("IsCredentialed", typeof(bool));
    
            var canRequestParameter = canRequest.HasValue ?
                new ObjectParameter("CanRequest", canRequest) :
                new ObjectParameter("CanRequest", typeof(bool));
    
            var callCarrierParameter = callCarrier != null ?
                new ObjectParameter("CallCarrier", callCarrier) :
                new ObjectParameter("CallCarrier", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var pictureParameter = picture != null ?
                new ObjectParameter("Picture", picture) :
                new ObjectParameter("Picture", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Web_SaveOnCallPeople", idParameter, onCAllPersonIDParameter, firstNameParameter, lastNameParameter, phoneNumberParameter, cellNOParameter, emailAddressParameter, practiceIdParameter, specialityIdParameter, isEmtalaParameter, isCredentialedParameter, canRequestParameter, callCarrierParameter, userIdParameter, pictureParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Web_SaveSpeciality(Nullable<long> id, string speciality, string description, Nullable<bool> isActive, Nullable<long> createdBy, Nullable<long> modifiedBy)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var specialityParameter = speciality != null ?
                new ObjectParameter("Speciality", speciality) :
                new ObjectParameter("Speciality", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(long));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Web_SaveSpeciality", idParameter, specialityParameter, descriptionParameter, isActiveParameter, createdByParameter, modifiedByParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Web_SaveUsers(Nullable<long> id, string firstName, string lastName, string password, Nullable<long> roleId, string userName, string emailId, string phone, Nullable<long> userId, Nullable<bool> isActive)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(long));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Web_SaveUsers", idParameter, firstNameParameter, lastNameParameter, passwordParameter, roleIdParameter, userNameParameter, emailIdParameter, phoneParameter, userIdParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<Web_Speciality_Result> Web_Speciality(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_Speciality_Result>("Web_Speciality", idParameter);
        }
    
        public virtual ObjectResult<Web_Users_Result> Web_Users(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_Users_Result>("Web_Users", idParameter);
        }
    
        public virtual ObjectResult<string> Usp_getRoleByUserID(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Usp_getRoleByUserID", userIdParameter);
        }
    
        public virtual ObjectResult<Usp_GetRoles_Result> Usp_GetRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetRoles_Result>("Usp_GetRoles");
        }
    
        public virtual ObjectResult<Web_GetUsers_Result> Web_GetUsers(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_GetUsers_Result>("Web_GetUsers", idParameter);
        }
    }
}
